### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of WEGN_RNFirebaseNotifications'

### ISSUE THREAD

**Issue by john1jan** [WebEngage/react-native-webengage#1] opened 2018-07-03 10:01 UTC
'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of WEGN_RNFirebaseNotifications'

Got this error when running on ios

**Comment by uzma-sayyed** [comment] 2018-07-05 05:56
@john1jan can you please provide more information on what action you are getting this error and how to reproduce it?

**Comment by Rajat421** [comment] 2018-07-18 05:11
@uzma-sayyed I am getting this error at runtime whenever I add WEGLicensecode in Info-plist.

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of WEGN_RNFirebaseNotifications'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bab81e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010a43e031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010babd472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010588864f -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   GrowwStage                          0x0000000102d75455 +[RCTEventEmitter initialize] + 325
	5   libobjc.A.dylib                     0x000000010a43eb04 CALLING_SOME_+initialize_METHOD + 19
	6   libobjc.A.dylib                     0x000000010a43ee9e _class_initialize + 276
	7   libobjc.A.dylib                     0x000000010a43c2f3 object_setClass + 90
	8   WebEngage                           0x000000010929d38e +[WEGDelegateProxy dynamicallySubclassAppDelegate:forProtocol:] + 2926
	9   WebEngage                           0x0000000109261fbe -[WebEngage swizzleUserNotificationCenterDelegate:] + 286
	10  WebEngage                           0x0000000109261e11 -[WebEngage observeValueForKeyPath:ofObject:change:context:] + 641
	11  Foundation                          0x00000001057c4820 NSKeyValueNotifyObserver + 349
	12  Foundation                          0x00000001057c40d7 NSKeyValueDidChange + 483
	13  Foundation                          0x00000001058a522b -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:usingBlock:] + 778
	14  Foundation                          0x00000001057911b4 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 61
	15  Foundation                          0x00000001057edb79 _NSSetObjectValueAndNotify + 255
	16  GrowwStage                          0x00000001031a14f6 -[RNFirebaseNotifications initialise] + 118
	17  GrowwStage                          0x00000001031a1450 -[RNFirebaseNotifications init] + 128
	18  GrowwStage                          0x0000000102dac894 __44-[RCTModuleData initWithModuleClass:bridge:]_block_invoke + 36
	19  GrowwStage                          0x0000000102dad3c2 -[RCTModuleData setUpInstanceAndBridge] + 1762
	20  GrowwStage                          0x0000000102daf0c6 __25-[RCTModuleData instance]_block_invoke + 38
	21  GrowwStage                          0x0000000102de3463 RCTUnsafeExecuteOnMainQueueSync + 67
	22  GrowwStage                          0x0000000102daedd2 -[RCTModuleData instance] + 754
	23  GrowwStage                          0x0000000102cfa838 __49-[RCTCxxBridge _prepareModulesWithDispatchGroup:]_block_invoke + 200
	24  libdispatch.dylib                   0x000000010d02c7ab _dispatch_call_block_and_release + 12
	25  libdispatch.dylib                   0x000000010d02d7ec _dispatch_client_callout + 8
	26  libdispatch.dylib                   0x000000010d038a3c _dispatch_main_queue_callback_4CF + 993
	27  CoreFoundation                      0x000000010ba7ac99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	28  CoreFoundation                      0x000000010ba3eea6 __CFRunLoopRun + 2342
	29  CoreFoundation                      0x000000010ba3e30b CFRunLoopRunSpecific + 635
	30  GraphicsServices                    0x000000010f516a73 GSEventRunModal + 62
	31  UIKit                               0x0000000107094057 UIApplicationMain + 159
	32  GrowwStage                          0x000000010285d79f main + 111
	33  libdyld.dylib                       0x000000010d0aa955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by Rajat421** [comment] 2018-07-18 07:01
@uzma-sayyed thanks, I have tried this but nothing changed still getting the same error

**Comment by sercanov** [comment] 2018-07-25 07:55
I also getting same error with react-native-firebase@4.3.0

**Comment by uzma-sayyed** [comment] 2018-07-25 10:00
Can you please try solutions given in this [thread](https://github.com/facebook/react-native/issues/8714)?

**Comment by saumitrabhave** [comment] 2018-08-16 13:04
I have created https://github.com/facebook/react-native/issues/20687 in React native , In the meantime (To temporarily fix crash) you can define `NS_BLOCK_ASSERTIONS` flag in Preprocessor Macros. You can do so by going to Build Target -> Build Settings -> Preprocessor Macros (Define for Debug).  

Hope this helps.

**Comment by sercanov** [comment] 2018-09-25 07:47
Any updates ? It is still crashing on debug mode, I have to comment out WebEngage initialize code every time

**Comment by saumitrabhave** [comment] 2018-09-26 13:01
Hi @sercanov , Did you try the workaround shared in in comment above? Does it solve the issue for you in debug mode

**Comment by sercanov** [comment] 2018-10-05 08:49
Hey @saumitrabhave 
I added `NS_BLOCK_ASSERTIONS=1` to Preprocessor Macros but it is still crashing

```
018-10-05 11:47:19.660073+0300 ] - [7446:1636090] -[WEGConfig initWithLuid:andCuid:] [Line 74] ERROR: Could Not create dataHolderContext Error Domain=NSCocoaErrorDomain Code=3840 "Cannot parse a NULL or zero-length data" UserInfo={NSDebugDescription=Cannot parse a NULL or zero-length data}
2018-10-05 11:47:19.668033+0300 - [7446:1636090] *** Assertion failure in +[RCTEventEmitter initialize](), /Users/sercanov/Projects/rider/node_modules/react-native/React/Modules/RCTEventEmitter.m:27
2018-10-05 11:47:19.669167+0300 - [7446:1636090] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of WEGN_RNFirebaseNotifications'
```

**Comment by rajatbeck** [comment] 2018-10-29 09:03
Facing the same issue , i have tried all the above mentioned solutions no success ,as this ticket is still open have you guys come up with any other solution?

**Comment by saumitrabhave** [comment] 2018-10-30 10:39
Hi, There is an open issue at https://github.com/facebook/react-native/issues/21333 , I don't think we can do much here. Did you try adding the flag as Preprocessor Macro for eg. https://stackoverflow.com/questions/30080466/disable-assertions-while-testing

**Comment by cayleyh** [comment] 2018-11-20 21:03
I'm getting this as well. I've tried adding the debug flag & it still doesn't work. In my case it looks like `RNFirebaseNotifications initialize` is triggering an observer in the `WebEngage` SDK that then tries to swizzle UserNotificationCenterDelegate (attached call stack).

However in my case, I'm NOT using the react-native-webengage package. I'm trying to use the native iOS SDK and incorporate it myself into a mixed project where I DON'T want to control WebEngage via react native code.

![screen shot 2018-11-20 at 1 02 50 pm](https://user-images.githubusercontent.com/118396/48802635-9c033080-ecc4-11e8-9bba-e1b1097142b7.png)

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of WEGN_RNFirebaseNotifications'
*** First throw call stack:
(0x18ef06fe0 0x18d968538 0x18ef06eb4 0x18f99f7cc 0x1003929e0 0x18d969418 0x18d969684 0x18d9666d8 0x101bf3c60 0x101bba3f0 0x101bba1f4 0x18f90cd08 0x18f90c830 0x18f9c3ac8 0x18f90bce4 0x18f930030 0x10063987c 0x1006397cc 0x1003c6ec0 0x1003c78c0 0x1003c93a4 0x1003f6120 0x1003c90d8 0x100322d7c 0x1020e9a50 0x1020e9a10 0x1020ee8b0 0x18eeb50c8 0x18eeb2ce4 0x18ede2da4 0x19084d074 0x19509dc9c 0x1000f48e0 0x18ddf159c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ygit** [comment] 2019-04-12 15:28
This was a pretty complicated issue to debug & resolve. We have released a fix for this in WebEngage iOS SDK version **4.5.0**

**Closed by ygit** 2019-04-12 15:28 UTC

**Comment by shafips** [comment] 2019-10-16 01:55
I am getting error with react-native 0.60.4

**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must override the `supportedEvents` method of WEGN_RNFirebaseNotifications'**

**Comment by ygit** [comment] 2019-10-16 08:48
@shafips Implement the steps mentioned on WebEngage Documentation for [Disable Swizzling](https://docs.webengage.com/docs/ios-advanced#section-7-disable-swizzling).
