### ISSUE TITLE
[iOS] duplicate symbol for architecture x86_64

### ISSUE THREAD

**Issue by wiedzmin26** [WebEngage/react-native-webengage#30] opened 2021-12-09 11:40 UTC
Hi,
Trying to run the code in the debug mode in simulator, but getting this error ->
duplicate symbol '_hasListeners' in:
    /Users/admin/Library/Developer/Xcode/DerivedData/TelganiApp-acygylkxltqzvealczpzsfuabuzv/Build/Products/Debug-iphonesimulator/RNZohoSalesIQ/libRNZohoSalesIQ.a(RNZohoSalesIQ.o)
    /Users/admin/Library/Developer/Xcode/DerivedData/TelganiApp-acygylkxltqzvealczpzsfuabuzv/Build/Products/Debug-iphonesimulator/react-native-webengage/libreact-native-webengage.a(WEGWebEngageBridge.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
![Zrzut ekranu 2021-12-9 o 12 38 05](https://user-images.githubusercontent.com/52349575/145389768-11ce7b84-2a8a-4ddd-8d23-e186568caffc.png)

I'm using this configuration :
react-native: 0.61.4
react-native-webengage: 1.2.10

Following are the pod file configurations
  pod 'react-native-webengage', :path => '../node_modules/react-native-webengage'

**Comment by uzma-sayyed** [comment] 2021-12-10 07:29
@wiedzmin26  can you please confirm the following in your project,
1. In Build Phases -> Compile Sources, check if any file is repeated for eg. 'main.m', if so remove one occurrence of that file.
2. If there is any subproject in your workspace that also has WebEngage framework, remove its pods project so that only one pods project should be there.

**Comment by wiedzmin26** [comment] 2021-12-10 11:12
@uzma-sayyed 
1. I only have two files 'main.m' and 'AppDelegate.m' with no duplicates.
2. There is only one project in my workspace. Before that, this library was not added. I'm doing it now.

**Comment by uzma-sayyed** [comment] 2021-12-10 12:15
@wiedzmin26 
this error seems to be coming due to a compilation error by react-native itself, can you please follow the below steps,
- If possible remove the Zoho Sale's framework using the "npm uninstall --save package_name" command
- Unlink it using "rnpm unlink package_name"
- Restart XCode
- Clear your project using cmd+shift+K
- Build and run on a new simulator

If the build succeeds you can add the ZohoSale package back.

**Comment by wiedzmin26** [comment] 2021-12-10 13:21
@uzma-sayyed 
After removing the 'react-native-zohosalesiq-mobilisten' package, the iOS code compiled and went on to run the iPhone 11 emulator. Unfortunately, the emulator had a bug related to react-native-zohosalesiq-mobilisten dependencies.

I still get the same error after adding 'react-native-zohosalesiq-mobilisten' again.

**Comment by uzma-sayyed** [comment] 2021-12-13 15:16
@wiedzmin26 as you mentioned looks like the issue is related to the other dependency in your project. Please report it to their support and let us know if anything is needed from our end.

**Comment by uzma-sayyed** [comment] 2021-12-14 05:27
@wiedzmin26, no file of WebEngage SDK uses the variable '_hasListeners' it is an attribute used by react-native itself while linking the frameworks at compile time. The build is failing because of either cocoa pods or react-native. Please try the following steps to link the frameworks manually,

- In project settings -> Build Phases tab -> Delete all files in `Link Binary With Libraries`
- Delete podfile.lock and Pods folder
- Quit Xcode and run `pod install`
- Clean and build your project

**Comment by uzma-sayyed** [comment] 2021-12-14 10:46
@wiedzmin26 publishing a new version of SDK might take time from our end, we will add this task in our pipeline and will update you once it is live. 
However the WebEngage bridge files are open source, you can rename the 'hasListeners' variable in the `webengageBridge.m` file and try it at your end.

**Comment by akshay-engage** [comment] 2023-09-12 06:12
Hi @wiedzmin26,

Thank you for bringing this issue to our attention. After careful consideration, it has been determined that the issue is not related to WebEngage but rather appears to be linked to another dependency in your project. As a result, we are closing this issue.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.

**Closed by akshay-engage** 2023-09-12 06:12 UTC
