### ISSUE TITLE
 Task :app:processReleaseManifest FAILED

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [WebEngage/react-native-webengage#39] opened 2022-08-22 10:48 UTC
Element uses-permission#android.permission.INTERNET at AndroidManifest.xml:15:1-63 duplicated with element declared at AndroidManifest.xml:8:5-67
android/app/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.webengage:android-sdk:3.21.1] /Users/siamcomputing/.gradle/caches/transforms-2/files-2.1/abb3ec7b371a5597a8bf6cc6948e645c/jetified-android-sdk-3.21.1/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.webengage.sdk.android" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

**Comment by SarthakWebEngage** [comment] 2022-09-12 06:40
Hi @Murugeshrockey-RN,
Is there any specific requirement for you to use the min version 16?
We have migrated our latest version to support min SDK 21. If you wish to use min SDK 16, then kindly downgrade the android-sdk dependency version by follow the steps:

In the app gradle of your application app/build.gradle add the following lines 
`configurations.all {
    resolutionStrategy {
        force 'com.webengage:android-sdk:3.20.5'
    }
}`

**Comment by akshay-engage** [comment] 2023-09-12 06:08
Hi @Murugeshrockey-RN ,

We have addressed the issue related to the minimum SDK version, and it appears to be resolved. As mentioned in our previous response, you can follow these steps to downgrade the android-sdk dependency version:

Since the issue is now resolved, we are closing this ticket.If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.

**Closed by akshay-engage** 2023-09-12 06:08 UTC
